# Generated by Django 5.1.2 on 2025-11-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_respuestatip'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(default='casa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default='casa', max_length=100),
            preserve_default=False,
        ),
    ]
