# Generated by Django 5.1.2 on 2025-11-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0004_publicacion_categoria_publicacion_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('enlace', models.URLField()),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
    ]
