# Generated by Django 5.1.2 on 2025-12-09 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_remove_cita_especialista_remove_cita_paciente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario_paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario_psicologo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='psicologo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
